export const industryLabels = {
    general: {
      customer: 'Customer',
      customers: 'Customers',
      lead: 'Lead',
      leads: 'Leads',
      buyer: 'Buyer',
      buyers: 'Buyers',
      deal: 'Deal',
      deals: 'Deals',
    },
    real_estate: {
      customer: 'Client',
      customers: 'Clients',
      lead: 'Seller Lead',
      leads: 'Seller Leads',
      buyer: 'Investor',
      buyers: 'Investors',
      deal: 'Property Deal',
      deals: 'Deals Closed',
    },
    wholesaler: {
      customer: 'Cash Buyer',
      customers: 'Buyers List',
      lead: 'Lead',
      leads: 'Leads',
      buyer: 'Buyer',
      buyers: 'Buyers',
      deal: 'Deal',
      deals: 'Deals',
    },
    pest_control: {
      customer: 'Customer',
      customers: 'Customers',
      lead: 'Lead',
      leads: 'Leads',
      buyer: 'Client',
      buyers: 'Clients',
      deal: 'Service',
      deals: 'Completed Jobs',
    },
    contractor: {
      customer: 'Client',
      customers: 'Clients',
      lead: 'Project Lead',
      leads: 'Leads',
      buyer: 'Homeowner',
      buyers: 'Homeowners',
      deal: 'Project',
      deals: 'Completed Projects',
    },
  };